### ISSUE TITLE
default install of the central-management does not allow https usage

### ISSUE THREAD

**Issue by igarny** [perfsonar/central-management#3]
On a default Debian install I do not get an https configuration for the services.
Is this a miss or is expected?

**Comment by laeti-tia** [comment]
Thanks for the report @igarny  This ticket should have been opened in the [maddash](https://github.com/esnet/maddash/issues) and [esmond](https://github.com/esnet/esmond/issues) repositories, this repo is for the central management scripts only (puppet and alike).  Unfortunately I cannot move it there as these repos are not under the perfsonar organisation.

**Comment by vvidic** [comment]
SSL enabled in the maddash Debian package. esmond does not seem to depend on mod_ssl in RHEL, so not adding it there.

**Comment by laeti-tia** [comment]
Confirmed working in 4.3.2 ;-)  No redirect is in place between HTTP and HTTPS because MaDDash is potentially hosted with other services and we don't want to mess with the whole Apache configuration as we do with the Toolkit.
